version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./core/static:/static
    depends_on:
      - core
    restart: always
  core:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: core
    command: sh -c "python3 manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - "8000"
    volumes:
      - .:/core
      - ./core/static:/core/static
    restart: always

  # main:
  #   container_name: main
  #   image: nginx:latest
  #   expose:
  #     - "8080"
  #   volumes:
  #     - ./main/nginx.conf:/etc/nginx/nginx.conf
  #   restart: always
  